name: Deploy to Google Cloud Run

'on': pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authorise Google Cloud
        uses: google-github-actions/auth@main
        with:
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: unibus-app

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: unibus-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy unibus-api-test \
            --source . \
            --region europe-west-1 \
            --allow-unauthenticated \
            --tag=$(echo "${GITHUB_REF_NAME}" | cut -c 1-30 | tr '[:upper:]' '[:lower:]')
            --no-traffic
