name: Deploy to App Engine on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/878954295159/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
          service_account: 'github-actions-app-engine@unibus-app.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: CI='' npm run build
      - name: Test
        run: GOOGLE_CREDENTIALS='${{ secrets.GOOGLE_CREDENTIALS }}' npm run test
      - id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          promote: false
