name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
      - setup-api-tests
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: CI='' npm run build
      - name: Start server
        run: npm run start
      - name: Test
        run: npm run test
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
