name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master # Set your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authorise Google Cloud
        uses: google-github-actions/auth@main
        with:
          credentials_json: ${{ secrets.GCP_SA }}
          project_id: unibus-app

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA }}
          project_id: unibus-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy unibus-api \
            --source .
            --region europe-west2
